[package]
name = "rusty-jvm"
version = "0.1.0"
authors = ["Mackie Loeffel <mackie.loeffel@web.de>"]

[dependencies]
classfile-parser = { git = "https://github.com/MackieLoeffel/classfile-parser.git" }
nom = "^2.1"

[features]
# treat warnings as errors
strict = []